Fix host splitting
The second parameter to `str.split()` is the maximum number of splits
to do, which means the list will have at most that many plus one
elements.

For strings which have more than 2 dots this causes an unintended
ValueError.

For example:

```
>>> host, vdc, _ = 'host-1.vdc.env'.split('.', 3)
>>> host, vdc, _ = 'host-1.vdc.env.computers.gov.uk'.split('.', 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
>>> host, vdc, _ = 'host-1.vdc.env.computers.gov.uk'.split('.', 2)
```